### ISSUE TITLE
Reactions on shared channels mix up team id's

### ISSUE THREAD

**Issue by twouters** [Sorunome/soru-slack-client#2]
A duplicate ghost with the local team as team id is invited if someone from the remote team adds a reaction (on a message of the local team - don't know if this is relevant) in a shared channel.

**Comment by Sorunome** [comment]
do you happen to have logs on how that slack payload looks like?

Am 7. April 2020 14:37:08 MESZ schrieb Thomas Wouters <notifications@github.com>:

**Comment by twouters** [comment]
```
Apr 07 12:00:07 midgard node[114006]: Apr-7 12:00:07.812 [SlackClient:Client] debug: RTM event: reaction_added
Apr 07 12:00:07 midgard node[114006]: Apr-7 12:00:07.816 [SlackPuppet:slack] verbose: Received new reaction
```

The last update removed my changes so I don't have the logs, will re-apply logging changes and keep an eye out for new events

**Comment by Sorunome** [comment]
Great, thank you

**Comment by Sorunome** [comment]
Is this fixed by now @twouters ?

**Comment by twouters** [comment]
I've seen reactions with the proper team id, so I think it's good now
