### ISSUE TITLE
Should not join channel on `channel_created` or `channel_renamed` events

### ISSUE THREAD

**Issue by twouters** [Sorunome/soru-slack-client#3]
This has been reported as Sorunome/mx-puppet-slack#53

According to the api docs `channel_created` (and `channel_renamed`) events should not join channels:

https://api.slack.com/events/channel_created
> The channel_created event is sent to all connections for a workspace when a new channel is created. Clients can use this to update their local cache of non-joined channels.

This bug leads to awkward situations where the bridge joins channels where it should not.  

`im_created` and `group_rename` events are only emitted to joined members, so those are fine.

**Comment by Sorunome** [comment]
fixed in https://github.com/Sorunome/soru-slack-client/commit/7eea083066e96dec7e6d7228f797ef73255b12bf
